### ISSUE TITLE
getReferences returning wrong references

### ISSUE THREAD

**Issue by Revadike** [goto-bus-stop/scope-analyzer#32]
# UPDATE
I found another project that offers more convenient and accurate reference/scope tracking:
https://github.com/PerimeterX/flast

*ORIGINAL:*
![image](https://user-images.githubusercontent.com/4411977/178166937-573b89f7-8c88-430a-8da1-7874c36e1bac.png)

For some reason here, the `root` property (of `root.root`) also returns the base object `root` as a reference, which is incorrect!

**Comment by goto-bus-stop** [comment]
I think this is because scope-analyzer only works with bare identifiers, it isn't able to trace properties. The AST for a property name is the same as the AST for a bare identifier (`{ type: 'Identifier', name: 'root' }`) so to scope-analyzer it looks like you're asking for references to a `root` variable.

It could be solved by having `getReferences` check if the node is a bare identifier, though I expect there are some tricky cases there. For example calling it on the left-hand-side of a MemberExpression is valid, but calling it on the right-hand-side of a MemberExpression is not.

**Comment by Revadike** [comment]
I tried something like that as a workaround, but it doesn't cover all cases. We need to find a way to do this properly. Somehow, VSCode can do this (with right click > find all references), so I know there must be a way to do it properly.

**Comment by goto-bus-stop** [comment]
AFAIK vscode uses the typescript compiler, which does much more advanced scope analysis than this package. tracing property usage is a non-goal for this package.

**Comment by goto-bus-stop** [comment]
I'll close this as i don't think there is an easy way to do it with how this package works now, and for my purposes, something difficult would not be worth the effort :) hopefully you found another way to do what you want!

**Comment by Revadike** [comment]
I did, a package called [flAST](https://www.npmjs.com/package/flast). It may be interesting for you too!
